apiVersion: v1
kind: ConfigMap
metadata:
  name: remote-postgresql-configmap
data:
  DATABASE_URL: "jdbc:postgresql://localhost:5432/apiexample?createDatabaseIfNotExist=true&stringtype=unspecified&useTimezone=true&serverTimezone=UTC"
  POSTGRES_USER: example
  DATABASE: apiexample
